DROP TABLE IF EXISTS buildings;
CREATE TABLE buildings (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    geom GEOMETRY(POLYGON)
);

DROP TABLE IF EXISTS roads;
CREATE TABLE roads (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    geom GEOMETRY(LINESTRING)
);

DROP TABLE IF EXISTS poi;
CREATE TABLE poi (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    geom GEOMETRY(POINT)
);